### ISSUE TITLE
Изменить детальную информацию по книге

### ISSUE THREAD

**Issue by gorohov09** [gorohov09/Library#22]
В методе API: [HttpGet("{ISBN}")]
1. Теперь, вместо списка всех экземпляров, нужно выводить количество экземпляров
2. Предлагаю создать дополнительный класс BookDetailsVm, который будет содержать необходимое поле с количеством и использовать этот тип в работе
3. Также не забыть удалить старое свойство из BookVm
4. Логику получения количества оставить за собой

**Comment by i-Nur23** [comment]
Под количеством понимаются все экземпляры или доступные в библиотеке на данный момент?

**Comment by gorohov09** [comment]
Количество доступных книг

**Comment by gorohov09** [comment]
Наверное, целесообразно будет создать новый метод в репозитории, которые возвращает это количество и заюзать его потом.
Но остается вопрос, как перевести это в тип BookDetailsVm. Я думаю, стоит сначала BookEntity перевести в BookDetailsVm при помощи Automapper, а потом свойство, отвечающее за количество в BookDetailsVm проинициализировать результатом работы метода
